### ISSUE TITLE
Create a GUI Version

### ISSUE THREAD

**Issue by absoluttechno** [ioncodes/JodelAPI#12]
Well, i tryed now so many times to use it, but i dont can.

I'm not a programer and cant use it, can you make a german tutorial for me? (i'm swiss)

This is a great work what you have done here!

If you would make a GUI version of this, for supereasy use, i would give you money! I like your work very but could not use it till today. I tryed so many times :/

**Comment by ioncodes** [comment]
Contact me via Gitter, I'm from switzerland too :)

**Comment by absoluttechno** [comment]
Gitter? Whats that mate?

Do you have line or whatsapp or facebook?


Or tell me how to use gitter

**Comment by ioncodes** [comment]
https://gitter.im/JodelAPI/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link
