### ISSUE TITLE
Location is always Bochum

### ISSUE THREAD

**Issue by GreenPIsoftware** [ioncodes/JodelAPI#13]
No matter what I try, the Jodels are always from Bochum.

**Comment by ioncodes** [comment]
I did notice this behavior in the new API already. I'm working on a fix for it which will be released in the dev branch first. Once the new API is done, it will be pushed to the master. Feel free to work with the dev-branch already! 
I think this bug has to do with the new verification process in jodel. Accounts now can be verified and the response json also contains it.

**Comment by CoffeeCodes** [comment]
v2 of the API was shut down. This was announced some weeks ago and since then, when you loaded Jodels there was a message that it would be discontinued. Use API v3.

**Comment by ioncodes** [comment]
Noticed it, thanks

**Comment by KirschbaumP** [comment]
I have noch Problems if I set tthe Location with "jodel.SetLocation();"

**Comment by ioncodes** [comment]
Can confirm that it works via SetLocation
