### ISSUE TITLE
Upvote not working after Token change

### ISSUE THREAD

**Issue by ioncodes** [ioncodes/JodelAPI#16]
If I upvote a jodel and generate a new token and i try to upvote it again, it will fail and say "not found" which is also thrown if a jodel has already been upvoted/downvoted with the same token. The server does still detect that we are the old user.

**Comment by CoffeeCodes** [comment]
You shall not upvote the same Jodel twice ;-) But it works. I am not sure what you do, but from what you say, I am guessing refreshing the token instead of getting a new one.

**Comment by ioncodes** [comment]
Hmm... I'm confused xD Which method do you call to assign a new token?

**Comment by CoffeeCodes** [comment]
GenerateAccessToken
And you have to be careful not to tell Jodel your old access token, as they will notice to what user it belongs. And not give you a new "clean" one.

**Comment by ioncodes** [comment]
Are you sure you're using the dev branch?

**Comment by CoffeeCodes** [comment]
Yes

**Comment by CoffeeCodes** [comment]
Well, it's your branch. If you don't understand the code you might want to be more careful what you pull requests you accept.... ;-)
But it works and it's not a bug.

**Comment by ioncodes** [comment]
I know, I found the bug, I worked on the methods aswell with KirschbaumP, but the problem was that Visual Studio didnt merge my old interfaces :D
