### ISSUE TITLE
Api too old

### ISSUE THREAD

**Issue by lectrasxt16** [ioncodes/JodelAPI#17]
"Hey Jodler, your version of the app is too old and won't be supported anymore???? Please update to the new and shiny Jodel and have fun??"

please fix!

**Comment by Snowfire01** [comment]
This is no bug, the API returns a Jodel with that content, when you are using an old version of the API (like you also would if you had an old version of Jodel installed on your phone).
You can still get all the Jodels, it just contains this on as the first element as a kind reminder to keep your app updated.

If you want to get rid of it by using the newest API version, consider to switch to the dev branch, where it is already implemented :)

**Comment by lectrasxt16** [comment]
Great thanks!
Is the dev version .net core compatible ?

**Comment by Snowfire01** [comment]
Most probably not. All API calls use the WebClient class which is not available in the .Net Core Framework (surely there are more examples like this, but I don't know for sure).

**Comment by lectrasxt16** [comment]
Okay,
I've now successfully ported the dev branch to .Net Core. 
If you want to include this in your repo, let me know!
