### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by ioncodes** [ioncodes/JodelAPI#18]
New generated accounts are not verified, they need to be verified by solving a captcha.

**Comment by KirschbaumP** [comment]
Can you show some mor information?
- Request and Response
- Version
- Device

**Comment by ioncodes** [comment]
if verified = false in the config, you will need to GET the captcha from this endpoint: user/verification/imageCaptcha
You will get an image, the string needs to be sent to the same endpoint via POST. The format is a JSON object with {'key':'', 'answer':''}. I don't know about the version and device, but i guess it's for all now (older app's will have problems because it's not implemented).
You can have a look here: https://bitbucket.org/cfib90/ojoc/commits/265110bb65b863980c054b4b48fe7fd2d4aa5a73
He implemented this already, I currently do not have enough time to fix this bug.

**Comment by ioncodes** [comment]
solved it
