### ISSUE TITLE
Gettin errors compiling

### ISSUE THREAD

**Issue by absoluttechno** [ioncodes/JodelAPI#2]
it says the file isn't in the exact Folder?

**Comment by absoluttechno** [comment]
![unbenannt42342324](https://cloud.githubusercontent.com/assets/20701401/20031546/c472641e-a379-11e6-8e89-09c8a6c5aa00.PNG)

**Comment by ioncodes** [comment]
Should work now. Pull the new version.

**Comment by absoluttechno** [comment]
![3w45rt](https://cloud.githubusercontent.com/assets/20701401/20031622/bade8530-a37a-11e6-9dc1-6b90345c047f.PNG)


not sure if, but thanks for helping me 👍

**Comment by absoluttechno** [comment]
can you solve all this Errors? :)

**Comment by ioncodes** [comment]
Can you try running Nuget restore? Right click on project at the right and click Nuget restore.

**Comment by absoluttechno** [comment]
ok, and know i have a build on /bin/debug is that right? it's jodelapi.ddl .jodelapi.pdb, Newtsonsoft.json.dll, Newtonsoft.json


how can i use now and "setup ?

**Comment by ioncodes** [comment]
Well tha's up to you how you use my library. Make a new C# Project, add it as reference and play around. However, you will need to wait a day, because the documentation/readme isn't updated.
(You will need JodelAPI.dll and Newtonsoft.Json.dll)

**Comment by absoluttechno** [comment]
yes i'm very interested in this tool.


can you make it run in console ?  oder even make an UI for this ? +REP

**Comment by ioncodes** [comment]
There is a console version in the repo JodelWindows. However it's not updated yet. Either you will update it and send me a pull request or wait couple of days.
