### ISSUE TITLE
Getting Bad Request WebExeption

### ISSUE THREAD

**Issue by Mese1953** [ioncodes/JodelAPI#38]
I'm trying to use the jodel API like your UnitTests.

```c#
    Jodel jodel = new Jodel("Zuerich Schweiz", "CH", "Zuerich");

    jodel.GenerateAccessToken();
    jodel.RefreshAccessToken();
    int karma = jodel.GetKarma();
```
But all request will end with the following Exception:
> System.Net.WebException occurred: The remote server returned an error: (400) Bad Request.

**Comment by Waterfront97** [comment]
I got the same problem with:

`Jodel jodel = new Jodel("Deutschland Dresden", "DE", "Dresden");`

**Comment by ioncodes** [comment]
I have to update the key, I will do this tomorrow

**Comment by ioncodes** [comment]
https://github.com/ioncodes/JodelAPI/commit/3931d3736ea7cc42aaa544dbb8e9d695af506d5a
Should be fixed now.

**Comment by Mese1953** [comment]
I got the same issue again. Where can we found the API keys to contribute these?

**Comment by Mese1953** [comment]
@ioncodes

**Comment by ioncodes** [comment]
Please have a look at this section https://github.com/ioncodes/JodelAPI#read-this-first
