### ISSUE TITLE
Gui edition

### ISSUE THREAD

**Issue by absoluttechno** [ioncodes/JodelAPI#6]
Can you create a simple gui for this? For easy use?

Regards

**Comment by ioncodes** [comment]
Depends on how you define gui, like, which features do you need etc.

**Comment by absoluttechno** [comment]
Create Account, up-downvote, edit votes, edit color, edit locationname, locationspoofer

**Comment by ioncodes** [comment]
I will not, however you can make one yourself or use the console. It shoud work if you use the new api.
